- name: Launch
        run: |
          # Permissions set karo
          chmod 600 ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config
          
          # Instance launch command
          oci compute instance launch \
          --availability-domain "AD-2" \
          --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
          --shape VM.Standard.A1.Flex \
          --shape-config '{"ocpus": 1, "memoryInGBs": 6}' \
          --image-id "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaada362yxj4vcvznlizmwszoen3rc56kz56tph4fe5wgsnp2p5o2xq" \
          --subnet-id "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaw5p45ihu62pmgextpupvbqpkblmhile5lsgsozqdrftz3cxjxrda" \
          --display-name "Sniper-Server"
